/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FHEComputationTestInterface extends Interface {
  getFunction(
    nameOrSignature: "testAddition" | "testComparison" | "testMultiplication"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "testAddition",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testComparison",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testMultiplication",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "testAddition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testComparison",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testMultiplication",
    data: BytesLike
  ): Result;
}

export interface FHEComputationTest extends BaseContract {
  connect(runner?: ContractRunner | null): FHEComputationTest;
  waitForDeployment(): Promise<this>;

  interface: FHEComputationTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  testAddition: TypedContractMethod<
    [requestId: string, data: BytesLike],
    [boolean],
    "nonpayable"
  >;

  testComparison: TypedContractMethod<
    [requestId: string, data: BytesLike],
    [boolean],
    "nonpayable"
  >;

  testMultiplication: TypedContractMethod<
    [requestId: string, data: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "testAddition"
  ): TypedContractMethod<
    [requestId: string, data: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "testComparison"
  ): TypedContractMethod<
    [requestId: string, data: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "testMultiplication"
  ): TypedContractMethod<
    [requestId: string, data: BytesLike],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
