/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IFHEComputationInterface extends Interface {
  getFunction(
    nameOrSignature: "getResult" | "performComputation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ComputationPerformed" | "ResultStored"
  ): EventFragment;

  encodeFunctionData(functionFragment: "getResult", values: [string]): string;
  encodeFunctionData(
    functionFragment: "performComputation",
    values: [string, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performComputation",
    data: BytesLike
  ): Result;
}

export namespace ComputationPerformedEvent {
  export type InputTuple = [requestId: string, encryptedResult: BytesLike];
  export type OutputTuple = [requestId: string, encryptedResult: string];
  export interface OutputObject {
    requestId: string;
    encryptedResult: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultStoredEvent {
  export type InputTuple = [requestId: string];
  export type OutputTuple = [requestId: string];
  export interface OutputObject {
    requestId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IFHEComputation extends BaseContract {
  connect(runner?: ContractRunner | null): IFHEComputation;
  waitForDeployment(): Promise<this>;

  interface: IFHEComputationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getResult: TypedContractMethod<[requestId: string], [string], "view">;

  performComputation: TypedContractMethod<
    [requestId: string, encryptedData: BytesLike, operationType: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<[requestId: string], [string], "view">;
  getFunction(
    nameOrSignature: "performComputation"
  ): TypedContractMethod<
    [requestId: string, encryptedData: BytesLike, operationType: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "ComputationPerformed"
  ): TypedContractEvent<
    ComputationPerformedEvent.InputTuple,
    ComputationPerformedEvent.OutputTuple,
    ComputationPerformedEvent.OutputObject
  >;
  getEvent(
    key: "ResultStored"
  ): TypedContractEvent<
    ResultStoredEvent.InputTuple,
    ResultStoredEvent.OutputTuple,
    ResultStoredEvent.OutputObject
  >;

  filters: {
    "ComputationPerformed(string,bytes)": TypedContractEvent<
      ComputationPerformedEvent.InputTuple,
      ComputationPerformedEvent.OutputTuple,
      ComputationPerformedEvent.OutputObject
    >;
    ComputationPerformed: TypedContractEvent<
      ComputationPerformedEvent.InputTuple,
      ComputationPerformedEvent.OutputTuple,
      ComputationPerformedEvent.OutputObject
    >;

    "ResultStored(string)": TypedContractEvent<
      ResultStoredEvent.InputTuple,
      ResultStoredEvent.OutputTuple,
      ResultStoredEvent.OutputObject
    >;
    ResultStored: TypedContractEvent<
      ResultStoredEvent.InputTuple,
      ResultStoredEvent.OutputTuple,
      ResultStoredEvent.OutputObject
    >;
  };
}
