/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFHEComputation,
  IFHEComputationInterface,
} from "../../../contracts/interfaces/IFHEComputation";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "requestId",
        type: "string",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "encryptedResult",
        type: "bytes",
      },
    ],
    name: "ComputationPerformed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "requestId",
        type: "string",
      },
    ],
    name: "ResultStored",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "requestId",
        type: "string",
      },
    ],
    name: "getResult",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "requestId",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "encryptedData",
        type: "bytes",
      },
      {
        internalType: "uint8",
        name: "operationType",
        type: "uint8",
      },
    ],
    name: "performComputation",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFHEComputation__factory {
  static readonly abi = _abi;
  static createInterface(): IFHEComputationInterface {
    return new Interface(_abi) as IFHEComputationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFHEComputation {
    return new Contract(address, _abi, runner) as unknown as IFHEComputation;
  }
}
