/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "FHEComputation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEComputation__factory>;
    getContractFactory(
      name: "FHEStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEStorage__factory>;
    getContractFactory(
      name: "IFHEComputation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFHEComputation__factory>;
    getContractFactory(
      name: "FHEComputationTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHEComputationTest__factory>;
    getContractFactory(
      name: "FhevmLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FhevmLib__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "FHEComputation",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEComputation>;
    getContractAt(
      name: "FHEStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEStorage>;
    getContractAt(
      name: "IFHEComputation",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFHEComputation>;
    getContractAt(
      name: "FHEComputationTest",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHEComputationTest>;
    getContractAt(
      name: "FhevmLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FhevmLib>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "FHEComputation",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEComputation>;
    deployContract(
      name: "FHEStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEStorage>;
    deployContract(
      name: "IFHEComputation",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFHEComputation>;
    deployContract(
      name: "FHEComputationTest",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEComputationTest>;
    deployContract(
      name: "FhevmLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FhevmLib>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "FHEComputation",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEComputation>;
    deployContract(
      name: "FHEStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEStorage>;
    deployContract(
      name: "IFHEComputation",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFHEComputation>;
    deployContract(
      name: "FHEComputationTest",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHEComputationTest>;
    deployContract(
      name: "FhevmLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FhevmLib>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
